server:
  port: 9001

spring:
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/major_switchMicroService
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.app.department: DEBUG  # Set this to your base package
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%X{traceId:-}, %X{spanId:-}] [${spring.application.name}] [%X{export:-}] [%thread] %logger{36} - %msg%n"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
